spring:
  config:
    activate:
      on-profile: dev
  application:
    name: employee-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: kk123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    config:
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
resilience4j:
  circuitbreaker:
    instances:
      employee-service:
        slidingWindowSize: 5
        register-health-indicator: true
        ringBufferSizeInClosedState: 5
        ringBufferInHalfOpenState: 5
        waitDurationInOpenState: 4s
        failureRateThreshold: 5
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
