spring:
  application:
    name: department-service
  cloud:
    config:
      uri: http://localhost:8888 
server:
  port: 8083
---  
  config:
    activate:
      on-profile: dev
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: kk123
  jpa:
    hibernate: 
      show-sql: true
      format-sql: true
      ddl-auto: update
    properties:
      hibernate: org.hibernate.dialect.PostgreSQLDialect
eureka:
  instance: localhost
  prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
