app:
  departmentURL: http://localhost:8082/department
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: kk123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    loadbalancer:
      retry:
        enabled: true
# This tells Eureka to try but not crash if unavailable
    discovery:
      enabled: true
    config:
      fail-fast: false

server:
  port: 8081

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 5

# THIS prevents crashing if Eureka is not reachable initially
  instance:
    prefer-ip-address: true


# IMPORTANT: Don't fail if Eureka is down
# This disables fatal startup if discovery fails
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  okhttp:
    enabled: true

